[project]
name = "ai-epub-translator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.7"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "dotenv>=0.9.9",
    "ebooklib>=0.20",
    "lxml>=6.0.2",
    "openai>=2.8.1",
]
